// Mocks generated by Mockito 5.4.5 from annotations
// in online_exam_app/test/features/home_screen/tabs/home_tab/presentation/cubit/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam_app/core/api_result/api_result.dart' as _i4;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/entities/response/get_all_subject_response_entity.dart'
    as _i5;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/usecases/get_all_subject_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetAllSubjectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllSubjectUseCase extends _i1.Mock
    implements _i2.GetAllSubjectUseCase {
  MockGetAllSubjectUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.GetAllSubjectsResponseEntity>> invoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.GetAllSubjectsResponseEntity>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.GetAllSubjectsResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.GetAllSubjectsResponseEntity>>);
}
