// Mocks generated by Mockito 5.4.5 from annotations
// in online_exam_app/test/features/home_screen/tabs/home_tab/api/data_source_impl/home_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/api/client/home_api_client.dart'
    as _i5;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/api/models/response/get_all_exam_on_subject_response_dto.dart'
    as _i4;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/api/models/response/get_all_subject_response_dto.dart'
    as _i3;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/api/models/response/get_exam_questions_response_dto.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExamResponseDto_0 extends _i1.SmartFake
    implements _i2.ExamResponseDto {
  _FakeExamResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllSubjectResponseDto_1 extends _i1.SmartFake
    implements _i3.GetAllSubjectResponseDto {
  _FakeGetAllSubjectResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllExamOnSubjectDto_2 extends _i1.SmartFake
    implements _i4.GetAllExamOnSubjectDto {
  _FakeGetAllExamOnSubjectDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i5.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ExamResponseDto> getExamQuestions(String? examId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamQuestions,
          [examId],
        ),
        returnValue:
            _i6.Future<_i2.ExamResponseDto>.value(_FakeExamResponseDto_0(
          this,
          Invocation.method(
            #getExamQuestions,
            [examId],
          ),
        )),
      ) as _i6.Future<_i2.ExamResponseDto>);

  @override
  _i6.Future<_i3.GetAllSubjectResponseDto> getAllSubjects() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSubjects,
          [],
        ),
        returnValue: _i6.Future<_i3.GetAllSubjectResponseDto>.value(
            _FakeGetAllSubjectResponseDto_1(
          this,
          Invocation.method(
            #getAllSubjects,
            [],
          ),
        )),
      ) as _i6.Future<_i3.GetAllSubjectResponseDto>);

  @override
  _i6.Future<_i4.GetAllExamOnSubjectDto> getAllExamOnSubject(
          String? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExamOnSubject,
          [subjectId],
        ),
        returnValue: _i6.Future<_i4.GetAllExamOnSubjectDto>.value(
            _FakeGetAllExamOnSubjectDto_2(
          this,
          Invocation.method(
            #getAllExamOnSubject,
            [subjectId],
          ),
        )),
      ) as _i6.Future<_i4.GetAllExamOnSubjectDto>);
}
