// Mocks generated by Mockito 5.4.5 from annotations
// in online_exam_app/test/features/home_screen/tabs/home_tab/data/repositories/home_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_app/core/api_result/api_result.dart' as _i4;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/data/datasources/home_remote_data_source.dart'
    as _i2;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/entities/request/get_all_exam_on_subject_request_entity.dart'
    as _i10;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/entities/request/get_exam_questions_request_Entity.dart'
    as _i6;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/entities/response/get_all_exam_on_subject_entity.dart'
    as _i9;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/entities/response/get_all_subject_response_entity.dart'
    as _i8;
import 'package:online_exam_app/features/home_screen/tabs/home_tab/domain/entities/response/get_exam_questions_response_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i2.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
      _i4.ApiResult<_i5.GetExamQuestionsResponseEntity>> getExamQuestions(
          _i6.GetExamQuestionsRequestEntity? getExamQuestionsRequestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamQuestions,
          [getExamQuestionsRequestEntity],
        ),
        returnValue: _i3
            .Future<_i4.ApiResult<_i5.GetExamQuestionsResponseEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.GetExamQuestionsResponseEntity>>(
          this,
          Invocation.method(
            #getExamQuestions,
            [getExamQuestionsRequestEntity],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.GetExamQuestionsResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.GetAllSubjectsResponseEntity>>
      getAllSubjects() => (super.noSuchMethod(
            Invocation.method(
              #getAllSubjects,
              [],
            ),
            returnValue: _i3
                .Future<_i4.ApiResult<_i8.GetAllSubjectsResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i8.GetAllSubjectsResponseEntity>>(
              this,
              Invocation.method(
                #getAllSubjects,
                [],
              ),
            )),
          ) as _i3.Future<_i4.ApiResult<_i8.GetAllSubjectsResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i9.GetAllExamOnSubjectEntity>> getAllExamOnSubject(
          _i10.GetAllExamOnSubjectRequestEntity?
              getAllExamOnSubjectRequestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExamOnSubject,
          [getAllExamOnSubjectRequestEntity],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i9.GetAllExamOnSubjectEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i9.GetAllExamOnSubjectEntity>>(
          this,
          Invocation.method(
            #getAllExamOnSubject,
            [getAllExamOnSubjectRequestEntity],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i9.GetAllExamOnSubjectEntity>>);
}
