name: online_exam_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_screenutil: ^5.9.3
  injectable:
  get_it:
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  retrofit: ^4.4.0
  logger: ^2.4.0 # for logging purpose
  json_annotation: ^4.9.0
  bloc: ^9.0.0
  fluttertoast: ^8.2.12
  flutter_bloc: ^9.1.1
  either_dart: ^1.0.0
  connectivity_plus: ^6.1.4
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.2.0
  equatable: ^2.0.7
  pinput: ^5.0.1
  shimmer: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_secure_storage: ^9.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  retrofit_generator: ">=8.0.0 <10.0.0" # for Dart 3.3 use ^9.0.0
  json_serializable: ^6.8.0
  test: ^1.25.8
  mockito: ^5.4.5
  bloc_test: ^10.0.0
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
